project:
  type: website

website:
  title: "Dr. Liam D. Bailey"
  site-url: "https://gorgeous-moxie-94ff8b.netlify.app/"
  navbar:
    search: false
    right:
      - href: blog.qmd
        text: blog
      - href: dataviz.qmd
        text: dataviz
      - href: assets/LiamDBailey_CV.pdf
        text: resume
      - icon: github
        href: https://github.com/LiamDBailey
        target: _blank
      - icon: twitter
        href: https://twitter.com/ldbailey255
        target: _blank
    collapse: false
    collapse-below: md
format:
  html:
    # theme:
    #   # Currently light and dark are the same
    #   light: [inst/css/base.scss, inst/css/theme_light.scss]
    #   dark:  [inst/css/base.scss, inst/css/theme_dark.scss]
    css: inst/css/base.css
    toc: true
    anchor-sections: false
    metadata:
      pagetitle: "Dr. Liam D. Bailey"
link-external-newwindow: true



