project:
  type: website

website:
  title: "Dr. Liam D. Bailey"
  site-url: "https://www.liamdbailey.com/"
  navbar:
    # left:
    #   - text: "CV"
    #   - file: assets/LiamDBailey_CV.pdf
    right:
      - href: blog.qmd
        text: blog
      - href: dataviz.qmd
        text: dataviz
      - href: assets/LiamDBailey_CV.pdf
        text: resume
      - icon: github
        href: https://github.com/LiamDBailey
      - icon: twitter
        href: https://twitter.com/ldbailey255
format:
  html:
    # theme:
    #   # Currently light and dark are the same
    #   light: [inst/css/base.scss, inst/css/theme_light.scss]
    #   dark:  [inst/css/base.scss, inst/css/theme_dark.scss]
    css: inst/css/base.css
    toc: true
    metadata:
      pagetitle: "Dr. Liam D. Bailey"



